- hosts: localhost
  become: true

  vars:
    packages:
      - htop
      - tilix
      - vim-enhanced
      - cpuid
      - tlp
      - tlp-rdw
      - neofetch
      - gnome-tweak-tool
      - transmission


  tasks:

  - name: enable google chrome repo
    shell: dnf config-manager --set-enabled google-chrome
    args:    
      warn: false


  - name: Install packages
    dnf: 
      pkg: "{{ packages }}"
      state: present
