- hosts: localhost
  become: true

  vars:
    packages:
      - htop
      - tilix
      - vim-enhanced
      - cpuid
      - tlp
      - tlp-rdw
      - neofetch
      - gnome-tweak-tool
      - transmission


  tasks:
  - name: Install packages
    dnf: 
      pkg: "{{ packages }}"
      state: present
