- hosts: localhost
  become: true

  vars:
    packages:
      - htop
      - tilix
      - vim-enhanced
      - cpuid
      - tlp
      - tlp-rdw
      - neofetch
      - gnome-tweak-tool
      - transmission
      - alsamixergui  # needed for thinkpad audio to work correctly
      - python3-tools # needed for python-idle
      - code # package name for MS Visual Studio Code
  tasks:

  - name: enable google chrome repo
    shell: dnf config-manager --set-enabled google-chrome
    args:    
      warn: false

  - name: Install key for MS VS Code
    rpm_key:
      state: present
      key: https://packages.microsoft.com/keys/microsoft.asc

  - name: Create repository for VS Code
    copy:
      src: /home/simon/git/files/vscode.repo
      dest: /etc/yum.repos.d/vscode.repo
      owner: root
      group: root
      mode: '0644'

  - name: Update DNF cache
    dnf:
    update_cache: yes

  - name: Install packages
    dnf: 
      pkg: "{{ packages }}"
      state: present
